#PARS shortcuts
#alias wrong_path='cd /state/partition1/milad/pin_wrong_path/source/tools/wrong_path/'
alias pars='cd /home/milad/esc_project/svn/PARS/src'
alias o3='cd /home/milad/esc_project/svn/PARS/src/backend/o3'
alias bb='cd /home/milad/esc_project/svn/PARS/src/backend/bb'
alias ino='cd /home/milad/esc_project/svn/PARS/src/backend/ino'
alias unit='cd /home/milad/esc_project/svn/PARS/src/backend/unit'
alias cash='cd /home/milad/esc_project/svn/PARS/src/backend/cache'
alias bp='cd /home/milad/esc_project/svn/PARS/src/backend/bp'
alias libr='cd /home/milad/esc_project/svn/PARS/src/lib'
alias glb='cd /home/milad/esc_project/svn/PARS/src/global'
alias frn='cd /home/milad/esc_project/svn/PARS/src/frontend'
alias bin='cd /home/milad/esc_project/svn/PARS/src/binaryTranslator'
alias rn='cd /home/milad/esc_project/svn/PARS/src/run'
alias cfg='cd /home/milad/esc_project/svn/PARS/src/config'
alias ub='cd /home/milad/esc_project/svn/PARS/benchmarks/ubench'
alias res='cd /scratch/milad/qsub_outputs/perf_sim_test/out2'
