#!/bin/sh

REG_ALLOC_MODE=$1
SCH_MODE=$2
CLUSTER_MODE=$3
CLUSTER_SIZE=$4
LOG_DIR="log"

 BENCH=400.perlbench
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=445.gobmk
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=464.h264ref
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=473.astar
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &

 BENCH=471.omnetpp
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=483.xalancbmk
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=462.libquantum
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=458.sjeng
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &

 BENCH=456.hmmer
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=429.mcf
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=401.bzip2
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &
 BENCH=403.gcc
 ./PhraseFormer $BENCH $REG_ALLOC_MODE $SCH_MODE $CLUSTER_MODE $CLUSTER_SIZE > $LOG_DIR/$BENCH &



#####
#./parse_x86.py cfg input_files/ $1 > input_files/input_assembly.s
#./PhraseFormer $BENCH
#cd dotFiles
#make
#cd ../
