---
cpu: 
    backend: 
        table: 
            QUE:
                size: 1000
                count: 1
                rd_wire_cnt: 1000
                wr_wire_cnt: 1000
                e_cam: 0
                e_ram: 0
                name: bbQUE
                type: FIFO
            ROB: 
                size: 100
                count: 1
                rd_wire_cnt: 32
                wr_wire_cnt: 32
                e_cam: 1
                e_ram: 1
                name: bbROB
                type: CAM
            LQ:
                size: 64
                count: 1
                rd_wire_cnt: 8
                wr_wire_cnt: 4
                e_cam: 1
                e_ram: 1
                name: LQtable
                type: CAM
            SQ:
                size: 32
                count: 1
                rd_wire_cnt: 8
                wr_wire_cnt: 4
                e_cam: 1
                e_ram: 1
                name: SQtable
                type: CAM
            resStn:
                size: 15
                count: 16
                rd_wire_cnt: 8
                wr_wire_cnt: 8
                e_cam: 1
                e_ram: 1
                name: resStn
                type: FIFO
            bbWindow:
                size: 15
                count: 16
                rd_wire_cnt: 8
                wr_wire_cnt: 8
                e_cam: 1
                e_ram: 1
                name: bbWindow_ #TODO get rid of _
                type: FIFO
            iWindow: #only for INO
                size: 120
                count: 1
                rd_wire_cnt: 4
                wr_wire_cnt: 4
                e_cam: 1
                e_ram: 1
                name: iWindow
                type: CAM
            mshr:
                size: 10
                count: 1
                rd_wire_cnt: 1
                wr_wire_cnt: 1
                e_cam: 1
                e_ram: 1
                name: MSHR
                type: RAM
            st_buff: #only for INO
                size: 20
                count: 1
                rd_wire_cnt: 4
                wr_wire_cnt: 4
                e_cam: 1
                e_ram: 1
                name: st_buff
                type: FIFO
