cache:
  physbits: 40 # number of bits in physical address
  size: 32768 # cache size in bytes
  bsize: 64 # block or line size
  assoc: 8 # associativity
  cin: 12 # maximum input capacitance in terms of lambda
